package com.pahappa.app.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;

/**
 * RoomQRSession — a short-lived QR code generated by the admin
 * and displayed on a screen inside the office.
 *
 * Two sessions are always generated together: one for CHECK_IN and one for
 * CHECK_OUT.  The type is embedded in the token payload so the server can
 * validate that an intern is using the correct code for the action they want
 * to perform.
 *
 * @author Pahappa
 * @version 1.0
 */
@Entity
@Table(name = "room_qr_sessions", indexes = {
    @Index(name = "idx_room_qr_token", columnList = "token"),
    @Index(name = "idx_room_qr_expires", columnList = "expires_at"),
    @Index(name = "idx_room_qr_type", columnList = "session_type")
})
public class RoomQRSession {

    /** Whether this code is for signing in or signing out */
    public enum SessionType { CHECK_IN, CHECK_OUT }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The unique random token encoded in the QR code.
     * Interns submit this token when checking in/out.
     */
    @Column(nullable = false, unique = true, length = 200)
    private String token;

    /** Whether this is a CHECK_IN or CHECK_OUT code */
    @Enumerated(EnumType.STRING)
    @Column(name = "session_type", nullable = false, length = 20)
    private SessionType sessionType;

    /** When this session was created */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** When this session expires */
    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    /** Whether this session has been explicitly invalidated by the admin */
    @Column(nullable = false)
    private boolean invalidated = false;

    /** Optional label shown on the display screen (e.g. "Morning session") */
    @Column(length = 100)
    private String label;

    public RoomQRSession() {}

    /**
     * Constructor with an explicit expiry timestamp and session type.
     */
    public RoomQRSession(String token, SessionType sessionType, LocalDateTime expiresAt, String label) {
        this.token = token;
        this.sessionType = sessionType;
        this.createdAt = LocalDateTime.now();
        this.expiresAt = expiresAt;
        this.label = label;
        this.invalidated = false;
    }

    /** True when the code can still be used */
    public boolean isValid() {
        return !invalidated && LocalDateTime.now().isBefore(expiresAt);
    }

    /** Seconds remaining until expiry (0 if already expired) */
    public long secondsRemaining() {
        long secs = java.time.Duration.between(LocalDateTime.now(), expiresAt).getSeconds();
        return Math.max(0, secs);
    }

    // ── Getters / Setters ────────────────────────────────────────────────────

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getToken() { return token; }
    public void setToken(String token) { this.token = token; }

    public SessionType getSessionType() { return sessionType; }
    public void setSessionType(SessionType sessionType) { this.sessionType = sessionType; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getExpiresAt() { return expiresAt; }
    public void setExpiresAt(LocalDateTime expiresAt) { this.expiresAt = expiresAt; }

    public boolean isInvalidated() { return invalidated; }
    public void setInvalidated(boolean invalidated) { this.invalidated = invalidated; }

    public String getLabel() { return label; }
    public void setLabel(String label) { this.label = label; }
    
    /**
     * Get the expiry time formatted with EAT timezone (Africa/Nairobi, UTC+3)
     * @return Formatted string like "2026-06-14 09:00:00 EAT"
     */
    public String getFormattedExpiresAt() {
        ZonedDateTime eatTime = expiresAt.atZone(ZoneId.of("Africa/Nairobi"));
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss 'EAT'");
        return eatTime.format(formatter);
    }
}
