package com.pahappa.app.repository;

import com.pahappa.app.entity.QRCodeSession;
import com.pahappa.app.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for QRCodeSession entity.
 * 
 * Provides CRUD operations and custom queries for QR code session management.
 * 
 * @author Pahappa
 * @version 1.0
 */
@Repository
public interface QRCodeSessionRepository extends JpaRepository<QRCodeSession, Long> {

    /**
     * Find QR code session by QR code data
     * @param qrCodeData The QR code data
     * @return Optional containing the QR code session
     */
    Optional<QRCodeSession> findByQrCodeData(String qrCodeData);

    /**
     * Find all QR code sessions for a user
     * @param user The user
     * @return List of QR code sessions
     */
    List<QRCodeSession> findByUserOrderByCreatedAtDesc(User user);

    /**
     * Count QR codes generated by user within a time range
     * @param user The user
     * @param startTime Start time
     * @param endTime End time
     * @return Count of QR codes generated
     */
    @Query("SELECT COUNT(q) FROM QRCodeSession q WHERE q.user = :user AND q.createdAt BETWEEN :startTime AND :endTime")
    long countByUserAndCreatedAtBetween(@Param("user") User user, @Param("startTime") LocalDateTime startTime, @Param("endTime") LocalDateTime endTime);

    /**
     * Find all expired QR codes
     * @param now Current time
     * @return List of expired QR code sessions
     */
    @Query("SELECT q FROM QRCodeSession q WHERE q.expiresAt < :now AND q.isUsed = false")
    List<QRCodeSession> findExpiredSessions(@Param("now") LocalDateTime now);

    /**
     * Find all valid (not used and not expired) QR codes for a user
     * @param user The user
     * @param now Current time
     * @return List of valid QR code sessions
     */
    @Query("SELECT q FROM QRCodeSession q WHERE q.user = :user AND q.isUsed = false AND q.expiresAt > :now ORDER BY q.createdAt DESC")
    List<QRCodeSession> findValidSessionsByUser(@Param("user") User user, @Param("now") LocalDateTime now);

    /**
     * Delete expired sessions older than a certain time
     * @param cutoffTime Cutoff time
     */
    @Query("DELETE FROM QRCodeSession q WHERE q.expiresAt < :cutoffTime")
    void deleteExpiredSessionsOlderThan(@Param("cutoffTime") LocalDateTime cutoffTime);

    /**
     * Check if user has any valid QR codes
     * @param user The user
     * @param now Current time
     * @return true if user has valid QR codes
     */
    @Query("SELECT CASE WHEN COUNT(q) > 0 THEN true ELSE false END FROM QRCodeSession q WHERE q.user = :user AND q.isUsed = false AND q.expiresAt > :now")
    boolean hasValidSession(@Param("user") User user, @Param("now") LocalDateTime now);
}

// Made with Bob